
export const BACKEND_PORT = process.env.NEXT_PUBLIC_BACKEND_PORT
export const EMPLOYEE_SERVICE = process.env.NEXT_PUBLIC_EMPLOYEE_SERVICE
export const MANAGER_SERVICE = process.env.NEXT_PUBLIC_MANAGER_SERVICE
export const ADMIN_SERVICE = process.env.NEXT_PUBLIC_ADMIN_SERVICE
export const OPENROUTER_API_KEY = process.env.NEXT_PUBLIC_OPENROUTER_API_KEY
export const JWT_SECRET = process.env.NEXT_PUBLIC_JWT_SECRET